name: Spring-boot CI with Gradle

on:
  push:
    branches:[ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'temurin'
          cache: gradle

     - name: Grant execute permisstion for gradlew
       run: chmod +x gradlew
     - name: Checked Code Format
       run: ./gradlew ktlintCheck
      # Run Test Case
      - name: Gradle Run Test
        run: ./gradlew test
